installation guide for windows
Bhupesh-V/ugit pull request #48
Opened 2022-08-24 17:05 UTC by vinayaknayar

Updated  the installation guide for windows.

2022-08-25 05:50 UTC, Bhupesh-V requested changes
This looks good, need some changes as requested.
Have you personally tried this approach to install ugit? Also I am assuming the approach is using the new WIndows Terminal right (As mentioned in https://github.com/Bhupesh-V/ugit/issues/20#issuecomment-1048234725?)

2022-08-25 05:50 UTC, Bhupesh-V commented on README.md
> +To use ugit on windows you need to install:<br>
```suggestion
To use `ugit` on windows, follow the steps below<br>
```

2022-08-25 05:50 UTC, Bhupesh-V commented on README.md
> +```
Can we use markdown lists instead of headings here?
As you mentioned there are a bunch of steps, it would be nice to have them as a list.

2022-08-25 06:37 UTC, vinayaknayar commented
yes i have personally tried this approach to install ugit using new windows terminal, and i will make the requested changes.

2022-08-25 06:51 UTC, vinayaknayar commented
i have updated the new commit. kindly review it.

2022-08-25 07:37 UTC, Bhupesh-V requested changes

2022-08-25 07:37 UTC, Bhupesh-V commented on README.md
> +* Git Bash<br>
Please use numbered lists. Like 1,2,3

2022-08-25 07:37 UTC, Bhupesh-V commented on README.md
> +```
Indent these code blocks to same level of list. If you are using VSCode please use the markdown preview feature

Edit the instructions like this
![de](https://user-images.githubusercontent.com/34342551/186604149-bcc1bb28-c888-48c1-8d3a-4ef2a6a04536.png)

2022-08-25 07:37 UTC, Bhupesh-V commented on README.md
> +To use ugit on windows you need to install:<br>
Please update this @vinayaknayar

2022-08-25 21:18 UTC, vinayaknayar commented
you can review it now!

2022-08-26 06:21 UTC, Bhupesh-V approved these changes

2022-08-26 06:21 UTC, merged

2022-08-26 06:22 UTC, Bhupesh-V commented
@all-contributors please add @vinayaknayar for doc