Add AUR to the README
Bhupesh-V/ugit pull request #5
Opened 2021-05-01 01:56 UTC by TabulateJarl8

There wasn't a feature branch so I'm doing this on master

2021-05-01 09:33 UTC, Nytelife26 commented
I would strongly suggest solely linking to the AUR and letting users figure out how best to install from it for their system on their own. This varies for many systems and there are no one size fits all instructions.

2021-05-03 23:56 UTC, TabulateJarl8 commented
I'm open to that as well, I'm just not too sure where I should put things and how to format it, so I'll change it if you have any good ideas about that

2021-05-04 11:40 UTC, Nytelife26 commented
> I'm open to that as well, I'm just not too sure where I should put
> things and how to format it, so I'll change it if you have any good
> ideas about that

I would suggest something along the lines of

```md
Or, Arch Users may install [ugit via the AUR][aur-ugit]

[aur-ugit]: https://aur.archlinux.org/packages/ugit
```

2021-05-05 06:47 UTC, Bhupesh-V commented on README.md
> +   or Arch Linux users can install ugit via the AUR
```suggestion
   Or Arch Linux users can install [**ugit via AUR**](https://aur.archlinux.org/packages/ugit)
```

2021-05-05 06:57 UTC, Bhupesh-V commented on README.md
> +   ```
No need

2021-05-05 06:57 UTC, Bhupesh-V requested changes
First of thanks a lot for checking out ugit and packaging it for AUR
I guess as @Nytelife26 pointed out linking the AUR would be just fine

Again, appreciate the effort 🙌🏽

2021-05-05 12:10 UTC, TabulateJarl8 commented
Sorry that I couldn't change it sooner, I had a power outage yesterday. It should be fixed now though

2021-05-05 13:32 UTC, Bhupesh-V approved these changes

2021-05-05 13:33 UTC, Bhupesh-V commented
> Sorry that I couldn't change it sooner, I had a power outage yesterday. It should be fixed now though

Thanks again for the contrib, 
Take care 😷 🛡️

2021-05-05 13:33 UTC, merged

2021-05-05 13:35 UTC, Bhupesh-V commented
@all-contributors please add @TabulateJarl8 for code and platform